"""Add progress column to jobs

Revision ID: e43964eacc09
Revises: e8d40c11c460
Create Date: 2025-11-30 20:21:30.446250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43964eacc09'
down_revision: Union[str, Sequence[str], None] = 'e8d40c11c460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('progress', sa.Integer(), server_default='0', nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_column('jobs', 'progress')
    # ### end Alembic commands ###
